### ISSUE TITLE
Some Bower dependencies are checked into version control

### ISSUE THREAD

**Issue by stdavis** [agrc/website#36]
![image](https://cloud.githubusercontent.com/assets/1326248/13849382/89451bfe-ec1b-11e5-99aa-37928e269599.png)

Not sure if this is intended or not but just thought that I would bring it up.

**Comment by steveoh** [comment]
jekyll doesn't installs deps, so they are checked in. I updated list.js as well until my pr gets accepted. It's not awesome but its how it has to work for the gh-pages branch setup to work.

**Comment by stdavis** [comment]
Understood.
